name: C++ CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env: 
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg 

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
    
    - name: Install Protobuf
      run: sudo apt install -y protobuf-compiler
    
    - name: Configure CMake
      run: cmake --preset default

    - name: Build project
      run: cmake --build build
    
    - name: Run tests
      run: ctest --test-dir build
